#!/usr/bin/env bash

# D E F A U L T S

sketchybar -m --bar                           \
position=top                                  \
height=26                                     \
margin=5                                     \
y_offset=10                                \
color="0x00000001"                            \
display=all                                   \
--default                                     \
associated_display=1                       
