#!/usr/bin/env bash

# Colors
source $HOME/.config/sketchybar/colors

BATTERY='
# Colors
source $HOME/.config/sketchybar/colors
BATT_PERCENT=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)
CHARGING=$(pmset -g batt | grep "AC Power")

if [[ $CHARGING != "" ]]; then
  sketchybar -m --set battery            \
    icon.color=0xFF${COLOR2:1}           \
    icon=🔌                              \
    label=$(printf "${BATT_PERCENT}%%") 
  exit 0
fi

[[ "${BATT_PERCENT}" -gt 10 ]] && COLOR="0xFF${COLOR5:1}" || COLOR="0xFF${COLOR1:1}"

case ${BATT_PERCENT} in
   100) ICON="🔋";;
    9[0-9]) ICON="🔋" ;;
    8[0-9]) ICON="🔋" ;;
    7[0-9]) ICON="🔋" ;;
    6[0-9]) ICON="🔋" ;;
    5[0-9]) ICON="🔋" ;;
    4[0-9]) ICON="🔋" ;;
    3[0-9]) ICON="🔋" ;;
    2[0-9]) ICON="🔋" ;;
    1[0-9]) ICON="⚡" ;;
    *) ICON="⚡"
esac

sketchybar -m --set battery           \
  icon.color="$COLOR"                 \
  icon="$ICON"                        \
  label=$(printf "${BATT_PERCENT}%%")
'

sketchybar -m --add item battery right                 \
              --set battery update_freq=3              \
              script="$BATTERY"                        \
              icon="🔋"                                \
              background.color="0x${BACKGROUND:1}"     \
	            background.border_width=1                \
	            background.border_color="0xFFffb86c"     \
              background.height=24                     \
              label.padding_right=15                   \
              label.padding_left=10                    \
              icon.padding_left=15                     \
              background.padding_left=15               \

