#!/usr/bin/env bash

# D E F A U L T S

sketchybar -m --bar                           \
position=top                                  \
height=26                                     \
color="0x00000000"                            \
display=all                                   \
--default                                     \
icon.font="VictorMono Nerd Font:Bold:12.0"    \
label.font="VictorMono Nerd Font:Italic:15.0" \
associated_display=1                       
