#!/usr/bin/env bash

# Colors
source $HOME/.config/sketchybar/colors

SCRIPT='
SPACE_TITLE=$(yabai -m query --spaces --space | jq .index | tr -d "\"")

sketchybar -m --set index label="$SPACE_TITLE"
'

# E V E N T S
sketchybar -m --add event space_changed

# W I N D O W  T I T L E 
sketchybar -m --add item index left                       \
	      --subscribe index space_changed		  \
              --set index script="$SCRIPT"                \
                label.color="0xFF${COLOR3:1}"             \
                label.padding_left=5                      \
                label.padding_right=6                     \
                background.height=24                      \
                background.color="0x${BACKGROUND:1}"      \
                background.border_width=1                 \
                background.border_color="0xFFffb86c"      \
